-- AlterTable
ALTER TABLE "attractions" ALTER COLUMN "startTime" DROP DEFAULT,
ALTER COLUMN "startTime" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "endTime" DROP DEFAULT,
ALTER COLUMN "endTime" SET DATA TYPE VARCHAR(128);
